### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by yutannihilation**
Clippy warnings are not necessarily what we must fix, but currently it's a bit annoying to see hundreds of warnings. Actually, this might make us to overlook some actual problems, so I want to clean up these by fixing, or suppressing if it's false-positive.

image

This pull request addresses the following warnings:

* [`clippy::clone_on_copy`](https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy)
* [`clippy::single_char_add_str`](https://rust-lang.github.io/rust-clippy/master/index.html#single_char_add_str)
* [`clippy::to_string_in_format_args`](https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args)
* [`clippy::useless_conversion`](https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion)
* [`clippy::useless_transmute`](https://rust-lang.github.io/rust-clippy/master/index.html#useless_transmute)
* [`clippy::vec_init_then_push`](https://rust-lang.github.io/rust-clippy/master/index.html#vec_init_then_push)

A full list of warnings can be found here:

https://gist.github.com/yutannihilation/991647186a8510f0bc0c7b8b34b45ee5

### CODE REVIEW

**Comment by DavisVaughan** [comment]
We don't actually use clippy, but we probably should, so that explains why it yells at you but not us

**Comment by DavisVaughan** [comment]
@yutannihilation after conf I definitely want us to start using clippy, but for the mass conversion to using clippy I'll probably do it a chunk at a time and then turn it on in `.vscode/settings.json` for all of us once we get everything resolved.

I do have a question though, is there any way to tell clippy to only warn about 1 lint at a time? Like, if I just want to see all cases of `clippy::clone_on_copy`, is there an easy way to do that? It would be much easier to produce and understand standalone commits like what you have here if so

**Comment by yutannihilation** [comment]
Glad to hear it!

> I do have a question though, is there any way to tell clippy to only warn about 1 lint at a time?

There might be a better way, but what I do is to specify `-A clippy::all` in order to suppress all the warnings and then specify one specific lint rule like below (Note that, some warnings like `dead_code` are not included in `clippy::all` because it comes from the compiler, not from clippy. I think I had to add several `-A` when I created this pull request)

```sh
cargo clippy -- -A clippy::all -W clippy::<some specific lint>
```

To do this, first I need to know the list of lint rules that the current code violates. I typically write out the full list of warnings to a text file, and process it.

``` console
❯ cargo clippy 2> tmp.txt

❯ grep -o -E 'https://.*index.html#.+' tmp.txt | sort | uniq -c
      9 https://rust-lang.github.io/rust-clippy/master/index.html#assign_op_pattern
      2 https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy
      1 https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_else_if
      1 https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_if
      2 https://rust-lang.github.io/rust-clippy/master/index.html#crate_in_macro_def
      1 https://rust-lang.github.io/rust-clippy/master/index.html#filter_next
      1 https://rust-lang.github.io/rust-clippy/master/index.html#legacy_numeric_constants
      2 https://rust-lang.github.io/rust-clippy/master/index.html#len_without_is_empty
      4 https://rust-lang.github.io/rust-clippy/master/index.html#len_zero
      3 https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
      1 https://rust-lang.github.io/rust-clippy/master/index.html#manual_flatten
      2 https://rust-lang.github.io/rust-clippy/master/index.html#manual_map
      2 https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro
     43 https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc
      1 https://rust-lang.github.io/rust-clippy/master/index.html#module_inception
     11 https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
      3 https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrows_for_generic_args
      4 https://rust-lang.github.io/rust-clippy/master/index.html#needless_question_mark
      5 https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
     39 https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
      1 https://rust-lang.github.io/rust-clippy/master/index.html#new_without_default
     80 https://rust-lang.github.io/rust-clippy/master/index.html#not_unsafe_ptr_arg_deref
      1 https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
      7 https://rust-lang.github.io/rust-clippy/master/index.html#ptr_offset_with_cast
      1 https://rust-lang.github.io/rust-clippy/master/index.html#redundant_slicing
      3 https://rust-lang.github.io/rust-clippy/master/index.html#redundant_static_lifetimes
     61 https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
      4 https://rust-lang.github.io/rust-clippy/master/index.html#single_char_add_str
      2 https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args
      1 https://rust-lang.github.io/rust-clippy/master/index.html#too_many_arguments
      1 https://rust-lang.github.io/rust-clippy/master/index.html#type_complexity
      2 https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
      4 https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
      3 https://rust-lang.github.io/rust-clippy/master/index.html#useless_transmute
      1 https://rust-lang.github.io/rust-clippy/master/index.html#vec_init_then_push
```
```

**Comment by DavisVaughan** [comment]
That's extremely helpful thank you!

**Pull request closed without merging**
